config/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from formulatracker import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('',include('formulatracker.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

config/formulatracker/urls.py
from django.urls import path
from . import views



app_name = 'feeds'

urlpatterns = [
    # User Login/Logout, Registration, & profile settings urls
    path('registration/',views.register,name='register'),
    path('password/', views.change_password, name='password'),
    path('password-success/', views.password_success,name='password_success'),
    path('edit_profile/',views.UserEditView.as_view(),name='edit_profile'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),

    # Feed Log urls
    path('feedlog/',views.feed_log_view,name='feedlog'),
    path('delete/<int:formulalog_id>/',views.feed_log_delete,name='delete'),

    #Chart data urls
    path('dailydata/',views.daily_data),
    path('monthdata/',views.monthly_data),
    path('weeklydata/', views.weekly_data),

    # Weight data urls
    path('weightlog/', views.weight_log, name='weightlog'),
    path('weightdelete/<int:weight_id>/',views.weight_log_delete,name='weightdelete'),
]

config/templates/base.html
<!DOCTYPE html>
{% load static %}
{% static "img/background.jpg" as background %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Formula Tracker{% endblock %}</title>

    <!-- Bootstrap Link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    
    <!-- Icons Link -->
    <script src="https://kit.fontawesome.com/3b7ab46358.js" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap' rel='stylesheet'>
    
    <!-- Custom styles -->
    <link href='{% static "css/styles.css" %}' rel='stylesheet'>
</head>

    <nav class="navbar navbar-dark navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'index' %}"><i class="fa-solid fa-baby fa-2x1"></i> Feeding Tracker</a>

			<button class="navbar-toggler ml-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
				<div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'feeds:feedlog' %}"><i class="fa-regular fa-rectangle-list"></i> {{user.child_name.capitalize}}'s Feed Dashboard</a>
                    <a class="nav-link" href="{% url 'feeds:weightlog' %}"><i class="fa-solid fa-scale-unbalanced"></i> {{user.child_name.capitalize}}'s Weight log</a>
                {% if user.is_superuser %}
                    <a class="nav-link" href="{% url 'admin:index' %}"><i class="fa-solid fa-lock"></i> Admin Dashboard</a>
                {% endif %}
                    <a class="nav-link" href="{% url 'feeds:edit_profile' %}"><i class="fa-regular fa-rectangle-list"></i> Settings</a>
                    <a class="nav-link" href="{% url 'feeds:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
                {% else %}
                    <a class="nav-link" href="{% url 'feeds:login' %}">Login</a>
                    <a class="nav-link" href="{% url 'feeds:register' %}">Register</a>
                {% endif %}
				</div>
            </div>
        </div>
    </nav>

<body class="body" style="background-image: url('{{ background }}');">
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <!-- Bootstrap Script -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    
    


    <footer class="py-4">
        <div class="d-flex align-items-center justify-content-center">
            <div class="text-center">
                Copyright &copy; <script>document.write(new Date().getFullYear())</script> Formula Tracker
            </div>
        </div>
    </footer>
</body>

</html>

config/templates/change-password.html
{% extends 'base.html' %}

<title>{% block title %}Feeding Tracker | Change Password{% endblock %}</title>

{% block body_block %}
<div class="py-4 mt-auto">
    <div class="container px-4">

        <div class="d-flex justify-content-center">
            <h2>Change Password</h2>
        </div>
        
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="card bg-seconday mb-3">
                    <div class="card-body">
                        
                        <div class="form-group">

                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p}}

                                <div class="form-group mt-4">
                                    <button type="submit" class="btn btn-primary">Change Password</button>
                                </div>
                            </form>
                            <br/>
                            <ul>
                                <li>Your password can't be too similar to your other personal information.</li>
                                <li>Your password must contain at least 8 characters.</li>
                                <li>Your password can't be a commonly used password.</li>
                                <li>Your password can't be entirely numeric.</li>
                            </ul>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

config/templates/chart.html
{% extends 'base.html' %}




<script>

var endpoint = '/options/'
var django = "{{ user_feed_log }}"
console.log(data)

$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        console.log(data)
        console.log(data.feed_amount)
    }
})



</script>

{% block body_block %}
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{% endblock %}

config/templates/edit_profile.html
{% extends 'base.html' %} 

{% block title %}Feed Tracker | User Settings{% endblock %}

{% block body_block %}
<div class="py-4 mt-auto">
    <div class="container px-4">

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <div class='row justify-content-center'>
            <div class='col-xl-12 mt-4'>

                <div class="row">
                    <div class="col-lg-6 offset-lg-3">
                        <div class="card bg-seconday mb-3 ">
                            <div class='card-header'>
                                <h5>Welcome, {{user.username.capitalize}}</h5>
                            </div>
                                <div class='card-body'>

                                    <div class="form-group">
                                        <form method="POST">
                                            {% csrf_token %}
                                            {{ form.as_p }}

                                            <div class="mt-2">Change password?<a href="{% url 'feeds:password' %}" type="button" class="btn btn-link">Click Here</a></div>

                                            <div class="col-lg-6">
                                                <button type="submit" class="btn btn-primary" style='margin-top:40px;'>Update Profile</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


<!-- <h1>Edit Profile</h1>
<br></br>

<div class="form-group">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Update Profile</button>
    </form>
</div> -->

config/templates/feed_log_delete.html
{% extends 'base.html' %}

{% block title %}Feed Tracker | Delete{% endblock %}

{% block body_block %}
<div class='py-4 mt-auto'>
    <div class='container-fluid px-4'>

        <h3>Feed Log</h3>

            <div class='row justify-content-center'>
                <div class='col-xl-12'>
                    <div class='card bg-secondary mb-3'>
                        <div class='card-body'>
    
                            <div class='form-group'>
                                <form method='POST'>
                                    {% csrf_token %}

                                    Are you sure you want to delete this entry item?
                                    <button type='submit' class='btn btn-danger'>Delete</button>

                                </form>

                            </div>

                        </div>
                    </div>
                </div>
            </div>

    </div>
</div>
{% endblock %}

config/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="container">
    <div class="bg-light text-black">

        <div>
            <div>
                
            </div>
        </div>
        <h1>Welcome!</h1>
    </div>
</div>
{% endblock %}

config/templates/login.html
{% extends 'base.html' %}

<title>{% block title %}Feeding Tracker | Login{% endblock %}</title>

{% block body_block %}
<div class="py-4 mt-auto">
    <div class="container px-4">

        <div class="d-flex justify-content-center">
            <h2>Login</h2>
        </div>
        
        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="card bg-seconday mb-3">
                    <div class="card-body">
                        
                        <div class="form-group">

                            <form action="{% url 'feeds:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="inputUsername" class="form-label mt-4">Username</label>
                                    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Enter Username">
                                </div>

                                <div class="form-group">
                                    <label for="inputPassword" class="form-label mt-4">Password</label>
                                    <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Enter Password">
                                </div>
                                
                                <div class="form-group mt-4">
                                    <button type="submit" class="btn btn-primary">Login</button>
                                </div>
                                <div class="mt-2">Don't have an account?<a href="{% url 'feeds:register' %}" type="button" class="btn btn-link">Register Here</a></div>
                            </form>

                            

                        </div>

                    </div>

                </div>
                
                
            </div>
        </div>

    </div>
</div>
{% endblock %}

config/templates/password-changed.html
{% extends 'base.html' %}

<title>{% block title %}Feeding Tracker | Password Changed{% endblock %}</title>

{% block body_block %}
<div class="py-4 mt-auto">
    <div class="container px-4">

        <div class="d-flex justify-content-center">
            <h2>Password was changed successfully!</h2>
        </div>

    </div>
</div>
{% endblock %}

config/templates/register.html
{% extends 'base.html' %}

{% block title %}Feeding Tracker | Registration{% endblock %}

{% block body_block %}
<div class="py-4 mt-auto">
    <div class="container px-4">

        <div class="d-flex justify-content-center">
            <h2>Register</h2>
        </div>

        {% if message %}
            <div>{{ message }}</div>
        {% endif %}

        <div class="row">
            <div class="col-lg-6 offset-lg-3">
                <div class="card bg-seconday mb-3 ">
                    <div class="card-body">
                        
                        <div class="form-group">
                            
                            <form action="{% url 'feeds:register' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="inputFirstname" class="form-label mt-4">First Name</label>
                                    <input type="text" name="firstname" class="form-control" id="inputFirstname" placeholder="Enter First Name">
                                </div>

                                <div class="form-group">
                                    <label for="inputLastname" class="form-label mt-4">Last Name</label>
                                    <input type="text" name="lastname" class="form-control" id="inputLastname" placeholder="Enter Last Name">
                                </div>

                                <div class="form-group">
                                    <label for="inputBirth" class="form-label mt-4">Date of Birth</label>
                                    <input type="date" name="birth" class="form-control" id="inputBirth" placeholder="Enter Date of Birth">
                                </div>

                                <div class="form-group">
                                    <label for="inputUsername" class="form-label mt-4">Username</label>
                                    <input type="text" name="username" class="form-control" id="inputUsername" placeholder="Enter Username">
                                </div>

                                <div class="form-group">
                                    <label for="inputEmail" class="form-label mt-4">Email</label>
                                    <input type="email" name="email" class="form-control" id="inputEmail" placeholder="Enter Email">
                                </div>

                                <div class="form-group">
                                    <label for="inputPassword" class="form-label mt-4">Password</label>
                                    <input type="password" name="password" class="form-control" id="inputPassword" placeholder="Enter Password">
                                </div>

                                <div class="form-group">
                                    <label for="inputConfirmation" class="form-label mt-4">Enter Password Again</label>
                                    <input type="password" name="confirmation" class="form-control" id="inputConfirmation" placeholder="Confirm Password">
                                </div>

                                <div class="form-group mt-4">
                                    <button type="submit" class="btn btn-primary">Register</button>
                                </div>

                            </form>

                            <div class="mt-2">Already have an account?<a href="#" type="button" class="btn btn-link">Log In Here</a></div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

config/templates/weight_dashboard.html
{% extends 'base.html' %}

{% load static %}
{% load filters %}
{% block title %}Feed Tracker | Weight Log{% endblock %}

{% block body_block %}
<div class='py-4 mt-auto'>
    <div class='container-fluid px-4'>

        <div class='row justify-content-center'>
            <div class='col-xl-12'>
                
                <div class='row g-3'>
                    <div class='col-md-6 mt-4'>
                        
                        <!-- ENTRY CARD -->
                        <div class='card shadow-sm h-100'>
                            <div class='card-header'>
                                <h2>Hi, {{user.username.capitalize}}!</h2>
                            

                            <div class="d-flex w-100 justify-content-between">
                                <p class='mb-1'>
                                    Last login: <strong>{{ user.last_login }}</strong>
                                </p>
                            </div>

                            
                            <div class="d-flex w-100 justify-content-between">
                                <p class='mb-1'>
                                    Date joined: <strong>{{ user.date_joined }}</strong>
                                </p>
                            </div>

                            </div>

                            <div class='card-body'>

                                <div class="form-group">
                                    <form method="POST">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <div class="row">

                                                <div>
                                                    <p class='mb-4'>
                                                        <h4>Add New Weight</h4>
                                                    </p>
                                                </div>

                                                <div class="col-lg-6">
                                                    <label for="weightdate" class="form-label mt-2">Date</label>
                                                    <input type="date" name="date" class="form-control" id="weightdate" placeholder="Date" required>
                                                </div>

                                                    <div class="col-sm-6">
                                                        <label for="weightamount" class="form-label mt-2">Current Weight</label>
                                                        <div class="input-group flex-nowrap">
                                                        {% if user.units == 'IMPERIAL' %}
                                                            <input type="number" name="lbs" class="form-control" id="weightamount" min="0" required>
                                                            <span class="input-group-text" id="units">Lbs</span>
                                                            <input type="number" name="oz" class="form-control" id="weightamount" min="0" required>
                                                            <span class="input-group-text" id="units">oz</span>
                                                        {% else %}
                                                            <input type="number" name="weight" class="form-control" id="weightamount" min="0" step="0.001" placeholder="Amount" required>
                                                            <span class="input-group-text" id="units">kg</span>
                                                        {% endif %}
                                                            

                                                        </div>
                                                    </div>

                                                    

                                                <div class="col-lg-6">
                                                    <button type="submit" class="btn btn-primary" style='margin-top:40px;'>Add Entry</button>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                    
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 mt-4">
                            <div class="card shadow-sm mb-3 h-100">
                                <div class="card-header">
                                    <h5>Weight Graphs</h5>
                                </div>
                                <div class="card-body bg-muted"> 
                                    <div class="chartBox">
                                        <canvas id="weightChart"></canvas>
                                    </div>
                                </div>
                            </div>
                        </div>
                            <!-- 
                                                                        FEEDINGS LOG TABLE CARD 

                            THIS IS WHERE THE CUSTOM FILTER TAG IS BEING USED TO CONVERT THE AMOUNT OF ENTRY TO METRIC BASED ON USER SETTINGS
                            -->
                        <div class="col-xl-12">
                            <div class="card shadow-sm mb-3">
                                <div class="card-header">
                                    <h5>Feeding Log for:</h5>
                                    <h5><strong class="text-primary" id="currentDate"></strong></h5>
                                </div>
                                <div class="card-body">
                                    <table id="weightTable" class="table table-hover shadow" style="text-align: center; vertical-align: middle;">
                                        <thead>
                                            <tr>
                                                <th scope="col" class="col-md-2">Date</th>
                                                {% if user.units == 'IMPERIAL' %}
                                                <th scope="col" class="col-md-2">Weight - Lbs & oz</th>
                                                {% else %}
                                                <th scope="col" class="col-md-2">Weight - Kg</th>
                                                {% endif %}
                                                <th scope='col' class='col-md-2'></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for entry in user_weight_log %}
                                            <tr>
                                                <td class="col md-2">{{ entry.date }}</td>
                                                {% if user.units == 'IMPERIAL' %}
                                                    <td class="col md-2">{{ entry.weight|convert_weights:user.units }}</td>
                                                {% else %}
                                                    <td class="col md-2">{{ entry.weight }}</td>
                                                {% endif %}
                                                <td>
                                                    <a class="btn btn-danger" href="{% url 'feeds:weightdelete' entry.id %}">
                                                        <i class="fa-solid fa-trash-can"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                            
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                </div>

            </div>
        </div>

    </div>
</div>

    <!-- Chart.js CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>

    <!-- Jquery Script -->
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>

    <!-- Feed Log JS -->
<script src="{% static 'js/weightlog.js' %}"></script>


{% endblock %}

config/templates/weight_log_delete.html
{% extends 'base.html' %}

{% block title %}Feed Tracker | Weight Delete{% endblock %}

{% block body_block %}
<div class='py-4 mt-auto'>
    <div class='container-fluid px-4'>

        <h3>Feed Log</h3>

            <div class='row justify-content-center'>
                <div class='col-xl-12'>
                    <div class='card bg-secondary mb-3'>
                        <div class='card-body'>
    
                            <div class='form-group'>
                                <form method='POST'>
                                    {% csrf_token %}

                                    Are you sure you want to delete this entry item?
                                    <button type='submit' class='btn btn-danger'>Delete</button>

                                </form>

                            </div>

                        </div>
                    </div>
                </div>
            </div>

    </div>
</div>
{% endblock %}